### ISSUE TITLE
MOD - Compile HEX

### ISSUE THREAD

**Issue by sarfat96** [LDmicro/LDmicro#28]
1. Modulo function is not work
2. When i try to "save as" ld file to different folder then i open it, i got some error when "Compile HEX". Because hex file not saved in new folder, but in old folder.

Thanks for LDmicro 👍

**Comment by LDmicroGitHub** [comment]
1. Labels means:
TODO: this feature in plan.
DONE: this feature is developed and tested. You can buy it.
EDIT: you can only edit LD file. Code for this feature will not generated.
You can buy it.

2. Will fixed in next release.

Regards,
Ihor




2017-05-26 11:04 GMT+03:00 William Sarfat <notifications@github.com>:
